### PR TITLE
Update espeak_wrapper.py - It would hang on Windows

### PR DESCRIPTION
**Pull request by erew123**
With Windows 11 (not tested other OS's) if you tried anything that interacted with espeak-ng, the process would hang e.g `E:\alltalk_tts\models\vits\tts_models--en--vctk--vits>tts --list_models`

The only way out was to ctrl+c, which gave the following:

```
........................etc
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\TTS\tts\utils\text\phonemizers\__init__.py", line 29, in <module>
    ESPEAK_LANGS = list(ESpeak.supported_languages().keys())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\TTS\tts\utils\text\phonemizers\espeak_wrapper.py", line 235, in supported_languages
    for count, line in enumerate(_espeak_exe(_DEF_ESPEAK_LIB, args, sync=True)):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\TTS\tts\utils\text\phonemizers\espeak_wrapper.py", line 80, in _espeak_exe
    res2 = list(res)
           ^^^^^^^^^
KeyboardInterrupt
^C
```

Both `espeak-ng --version` and `espeak-ng --voices` was fine at the command prompt and in the system wide PATH environment variable, so it came down to how the script was reading output from the subprocess. Its been changed to a while loop to ensure it can read the output correctly and avoid any buffering issues. Espeak-ng has had the `q` switch applied to stop it speaking anything when TTS is generated. 

The key change is in `def _espeak_exe` and it should work fine across all OS's

Thanks for keeping going with the TTS engine!

### CODE REVIEW

**Comment by eginhard** [comment]
Thanks a lot for the PR! I was able to reproduce the issue (#24) in a Windows VM and will test it on my side.

**Comment by erew123** [comment]
FYI, just manage to test this on Ubuntu 22.04.4 and it ran fine! :)

**Comment by eginhard** [comment]
Thanks again for the PR and testing! I ended up taking a slightly different approach in #34 by switching to `subprocess.run` which simplifies that whole function a lot and I also added a fix for another Windows Espeak bug. I confirmed it works on Ubuntu and the Windows VM, but would you be able to test it as well to be sure? I'll release a version with those fixes asap then.

**Comment by erew123** [comment]
Just checked and Windows + Ubuntu look happy to me :)

image

Its a real boost to have the Coqui TTS updated. It was something I thought I would have to attempt myself at some point. The requirements were getting quite restrictive and my own project (AllTalk) was probably going to be complicated by some of the version 2 requirements (currently writing v2 https://github.com/erew123/alltalk_tts/discussions/211)

Can I ask you a simple question here... I assume the training code/imports are still the same currently?

Also, I had to update the tokenizer to work with Japanese https://github.com/erew123/alltalk_tts/blob/main/system/ft_tokenizer/tokenizer.py

That would be handy to have incorporated if you haven't already?

**Comment by eginhard** [comment]
Sure, you can link to this repo (although the old one also still has a lot of useful information in issues and discussions, I should probably mention that in the readme here).

I just released 0.24.1 with the fix.

**Pull request closed without merging**
